pipeline:
    build:
        image: openjdk:8
        commands:
            - mvn package
    slack:
        image: plugins/slack
        webhook:  https://hooks.slack.com/services/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
        channel: soa_team_h
        username: Drone
        when:
            status: [ success, failure ]
        template: >
            {{#success build.status}}
                build {{build.number}} succeeded. Good job.
            {{else}}
                build {{build.number}} failed. Fix me please.
            {{/success}}